### ISSUE TITLE
Problem with installation on windows machine

### ISSUE THREAD

**Issue by federikovi** [wellcometrust/WellcomeML#257] opened 2021-03-24 16:18 UTC
I've tried to install wellcomeML on my Windows machine with `pip install wellcomeml[deep-learning]` before reading the specific windows [instructions](https://github.com/wellcometrust/WellcomeML). 
So I created a separate environment and installed wellcomeML with this two commands:

`pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html`

`pip install wellcomeml[deep-learning]`

When I try to run some experiments like [text clustering](https://github.com/wellcometrust/WellcomeML/blob/main/examples/text_clustering.py) from the _Examples_ folder, it returns me this error message right from the importing line `from wellcomeml.ml import TextClustering`:

```
2021-03-24 16:58:40 wellcomeml.logger WARNING: If you want to use hdbscan you need to runpip3 install hdbscan --no-cache-dir --no-binary :all: --no-build-isolation Read more https://github.com/wellcometrust/WellcomeML/issues/197
2021-03-24 16:58:44 wellcomeml.logger ERROR: cannot import name 'structref' from 'numba.experimental' (C:\Users\feder\anaconda3\lib\site-packages\numba\experimental\__init__.py)
2021-03-24 16:58:44 wellcomeml.logger WARNING: Using WellcomeML without extras (transformers & torch).
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-75dd66ac4ed0> in <module>
----> 1 from wellcomeml.ml import TextClustering

ImportError: cannot import name 'TextClustering' from 'wellcomeml.ml' (C:\Users\feder\anaconda3\lib\site-packages\wellcomeml\ml\__init__.py)
```

I'm on Windows 10 version `20H2`, my python version `3.8.3`.

This is my current pip freeze: [pip list.txt](https://github.com/wellcometrust/WellcomeML/files/6198832/pip.list.txt)

I guess there must be some conflicts between the installations, I should probably uninstall and reinstall the library.

**Comment by aCampello** [comment] 2021-03-24 16:27
Thank you very much for opening this issue @federikovi. We suffer from the fact that most of us develop the library on a bash-type environment (Linux/Mac), so we do bump into Windows conflict from time to time. 

That said, your error seems to be weird. Could you try and re-create an environment and only install wellcomeml by doing

```bash
pip install wellcomeml[deep-learning] --upgrade --no-cache-dir
```

It seems that `numba==0.53.0` does have `experimental.structuref` in it, so probably your environment is getting an older version of it somehow?

**Comment by aCampello** [comment] 2021-03-24 16:29
As a workaround, you can probably get around the error by changing the import in the example file from
```python
from wellcomeml.ml import TextClustering
```
to
```python
from wellcomeml.ml.clustering import TextClustering
```

**Comment by nsorros** [comment] 2021-03-24 16:46
Let's try to reproduce the error on our machines to see whether the problem is related to the libraries at least. Also it would be nice to test WellcomeML against Windows, we can do that in Travis by changing the machine image.

**Comment by aCampello** [comment] 2021-03-24 16:48
> Let's try to reproduce the error on our machines to see whether the problem is related to the libraries at least. Also it would be nice to test WellcomeML against Windows, we can do that in Travis by changing the machine image.

Yes! https://github.com/wellcometrust/WellcomeML/issues/258

**Comment by nsorros** [comment] 2021-03-25 07:13
I am starting the process of recreating the error and will update shortly.

**Comment by federikovi** [comment] 2021-03-25 09:08
**Update:** I have installed the library on a new environment correctly and it seems to work so far, my only suggestion for this is to specify in the installation instructions that `pip install wellcomeml` is only for Mac/Linux machines. Just by putting an header would lead windows users to scroll down for the right installation instructions.

The TextClustering import worked correctly both with both commands:

`from wellcomeml.ml import TextClustering` and `from wellcomeml.ml.clustering import TextClustering`

However, when running the [text clustering example](https://github.com/wellcometrust/WellcomeML/blob/main/examples/text_clustering.py) I had this error:

`OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
`
That has been simply solved by installing spacy with pip:

```
pip install spacy
python -m spacy download en_core_web_sm
```
and loading spacy on the notebook
```
import spacy
spacy.load("en_core_web_sm")
```

***

I've also played with [Bert classifier](https://github.com/wellcometrust/WellcomeML/blob/main/examples/bert_classifier.py) and it works.

**Comment by nsorros** [comment] 2021-03-25 09:14
> **Update:** I have installed the library on a new environment correctly and it seems to work so far, my only suggestion for this is to specify in the installation instructions that `pip install wellcomeml` is only for Mac/Linux machines. Just by putting an header would lead windows users to scroll down for the right installation instructions.
> 
> The TextClustering import worked correctly both with both commands:
> 
> `from wellcomeml.ml import TextClustering` and `from wellcomeml.ml.clustering import TextClustering`
> 
> However, when running the [text clustering example](https://github.com/wellcometrust/WellcomeML/blob/main/examples/text_clustering.py) I had this error:
> 
> `OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory. `
> That has been simply solved by installing spacy with pip:
> 
> ```
> pip install spacy
> python -m spacy download en_core_web_sm
> ```
> 
> and loading spacy on the notebook
> 
> ```
> import spacy
> spacy.load("en_core_web_sm")
> ```
> 
> I've also played with [Bert classifier](https://github.com/wellcometrust/WellcomeML/blob/main/examples/bert_classifier.py) and it works.

Glad to hear it is working, I suppose you recreated the environment using wellcomeml in your dependencies. If this solved your problem it is possibly due to a version incompatibility described above. The way pip works, it only checks for compatible when you install all of the libraries together so for example `pip install numpy tensorflow` is different from `pip install numpy && pip install tensorflow` in the sense that in the second it does not ensure all dependencies match which is possibly what happened when you installed wellcomeml in an already created environment. Hope that makes sense.

That said I think we need to improve on the way we handle errors in `wellcomeml.ml.__init__` as anything that causes an error throws a similar looking error with no guidance to the user. I will open an issue about this.

**Comment by federikovi** [comment] 2021-03-25 09:27
@nsorros Yes it kinda makes sense! I must have also created some confusion with various installations and environments that didn't help. On the current one it works. 

I updated pip before installing the library this morning. The current version is `20.1.1`, I guess the conflicts came from the earlier pip version too. Should i close this issue?

**Comment by nsorros** [comment] 2021-03-25 09:36
> @nsorros Yes it kinda makes sense! I must have also created some confusion with various installations and environments that didn't help. On the current one it works.
> 
> I updated pip before installing the library this morning. The current version is `20.1.1`, I guess the conflicts came from the earlier pip version too. Should i close this issue?

Yep do close it, we will open other issues for the various things we want to improve.

**Closed** 2021-03-25 09:45 UTC
Labels: bug
